In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/sample_data/california_housing_train.csv")

In [ ]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

In [ ]:
df["housing_median_age"]

0        15.0
1        19.0
2        17.0
3        14.0
4        20.0
         ... 
16995    52.0
16996    36.0
16997    17.0
16998    19.0
16999    52.0
Name: housing_median_age, Length: 17000, dtype: float64

In [ ]:
df.columns[2]

'housing_median_age'

In [ ]:
df[df.columns[2]]

0        15.0
1        19.0
2        17.0
3        14.0
4        20.0
         ... 
16995    52.0
16996    36.0
16997    17.0
16998    19.0
16999    52.0
Name: housing_median_age, Length: 17000, dtype: float64

In [ ]:
df=df.replace(to_replace='na',value=np.nan)
#replaces na in the data set

In [ ]:
df.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [ ]:
df.iloc[3:16997,2:5]

housing_median_age  total_rooms  total_bedrooms
3                    14.0       1501.0           337.0
4                    20.0       1454.0           326.0
5                    29.0       1387.0           236.0
6                    25.0       2907.0           680.0
7                    41.0        812.0           168.0
...                   ...          ...             ...
16992                52.0       1112.0           209.0
16993                52.0       2694.0           453.0
16994                32.0       1430.0           419.0
16995                52.0       2217.0           394.0
16996                36.0       2349.0           528.0

[16994 rows x 3 columns]

In [ ]:
arr = np.array([0,3,5])

In [ ]:
df.iloc[1:16997,arr]

longitude  total_rooms  population
1        -114.47       7650.0      1129.0
2        -114.56        720.0       333.0
3        -114.57       1501.0       515.0
4        -114.57       1454.0       624.0
5        -114.58       1387.0       671.0
...          ...          ...         ...
16992    -124.23       1112.0       544.0
16993    -124.23       2694.0      1152.0
16994    -124.25       1430.0       434.0
16995    -124.26       2217.0       907.0
16996    -124.27       2349.0      1194.0

[16996 rows x 3 columns]

In [ ]:
arr

array([0, 3, 5])

In [ ]:
#column of correct ans is also known as ground truth column

In [ ]:
#scania aps failure dataset- very challenging dataset

In [ ]:
x=df.iloc[:,0:8]

In [ ]:
y=df.iloc[:,8:9]

In [ ]:
x

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  
0          1015.0       472.0         1.4936  
1          1129.0       463.0         1.8200  
2           333.0       117.0         1.6509  
3           515.0       226.0         3.1917  
4           624.0       262.0         1.9250  
...           ...         ...            ...  
16995       907.0       369.0         2.3571  
16996      1194.0       465.0         2.5179  
16997      1244.0       456.0         3.0313  
16998      1298.0       478.0         1.9797  
16999       806.0       270.0         3.0147  

[17000 rows x 8 columns]

In [ ]:
y

median_house_value
0                 66900.0
1                 80100.0
2                 85700.0
3                 73400.0
4                 65500.0
...                   ...
16995            111400.0
16996             79000.0
16997            103600.0
16998             85800.0
16999             94600.0

[17000 rows x 1 columns]

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:

algo = LinearRegression()

In [ ]:
algo.fit(x,y)

LinearRegression()

In [ ]:
machine_predictions = algo.predict(x)

In [ ]:
machine_predictions

array([[  7128.08452517],
       [ 73675.60144224],
       [-31317.28531191],
       ...,
       [100878.32872671],
       [ 63733.22144717],
       [186850.92450275]])

In [ ]:
mse = np.mean((machine_predictions - y)**2)

/usr/local/lib/python3.9/dist-packages/numpy/core/fromnumeric.py:3472: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


In [ ]:
#mean squares error
mse

median_house_value    4.824523e+09
dtype: float64

In [ ]:
rmse = np.sqrt(mse)

In [ ]:
#root mean squared error
rmse

median_house_value    69458.787593
dtype: float64

In [ ]:
#rmse is high so in order to reduce it we have to try removing unneccesary columns

In [ ]:
data_correlation=df.corr()

In [ ]:
data_correlation

longitude  latitude  housing_median_age  total_rooms  \
longitude            1.000000 -0.925208           -0.114250     0.047010   
latitude            -0.925208  1.000000            0.016454    -0.038773   
housing_median_age  -0.114250  0.016454            1.000000    -0.360984   
total_rooms          0.047010 -0.038773           -0.360984     1.000000   
total_bedrooms       0.071802 -0.069373           -0.320434     0.928403   
population           0.101674 -0.111261           -0.295890     0.860170   
households           0.059628 -0.074902           -0.302754     0.919018   
median_income       -0.015485 -0.080303           -0.115932     0.195383   
median_house_value  -0.044982 -0.144917            0.106758     0.130991   

                    total_bedrooms  population  households  median_income  \
longitude                 0.071802    0.101674    0.059628      -0.015485   
latitude                 -0.069373   -0.111261   -0.074902      -0.080303   
housing_median_age       -0.320434   -0.295890   -0.302754      -0.115932   
total_rooms               0.928403    0.860170    0.919018       0.195383   
total_bedrooms            1.000000    0.881169    0.980920      -0.013495   
population                0.881169    1.000000    0.909247      -0.000638   
households                0.980920    0.909247    1.000000       0.007644   
median_income            -0.013495   -0.000638    0.007644       1.000000   
median_house_value        0.045783   -0.027850    0.061031       0.691871   

                    median_house_value  
longitude                    -0.044982  
latitude                     -0.144917  
housing_median_age            0.106758  
total_rooms                   0.130991  
total_bedrooms                0.045783  
population                   -0.027850  
households                    0.061031  
median_income                 0.691871  
median_house_value            1.000000

In [ ]:
correct_ans_correlation=data_correlation[df.columns[-1]]

In [ ]:
columns_list=pd.DataFrame(correct_ans_correlation[(correct_ans_correlation<-0.14) | (correct_ans_correlation>0.1)])
#boolean masking

In [ ]:
columns_list.index

Index(['latitude', 'housing_median_age', 'total_rooms', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
filtered_data=df[columns_list.index]

In [ ]:
filtered_data

latitude  housing_median_age  total_rooms  median_income  \
0         34.19                15.0       5612.0         1.4936   
1         34.40                19.0       7650.0         1.8200   
2         33.69                17.0        720.0         1.6509   
3         33.64                14.0       1501.0         3.1917   
4         33.57                20.0       1454.0         1.9250   
...         ...                 ...          ...            ...   
16995     40.58                52.0       2217.0         2.3571   
16996     40.69                36.0       2349.0         2.5179   
16997     41.84                17.0       2677.0         3.0313   
16998     41.80                19.0       2672.0         1.9797   
16999     40.54                52.0       1820.0         3.0147   

       median_house_value  
0                 66900.0  
1                 80100.0  
2                 85700.0  
3                 73400.0  
4                 65500.0  
...                   ...  
16995            111400.0  
16996             79000.0  
16997            103600.0  
16998             85800.0  
16999             94600.0  

[17000 rows x 5 columns]

In [ ]:
x=filtered_data.iloc[:,0:4]

In [ ]:
x

latitude  housing_median_age  total_rooms  median_income
0         34.19                15.0       5612.0         1.4936
1         34.40                19.0       7650.0         1.8200
2         33.69                17.0        720.0         1.6509
3         33.64                14.0       1501.0         3.1917
4         33.57                20.0       1454.0         1.9250
...         ...                 ...          ...            ...
16995     40.58                52.0       2217.0         2.3571
16996     40.69                36.0       2349.0         2.5179
16997     41.84                17.0       2677.0         3.0313
16998     41.80                19.0       2672.0         1.9797
16999     40.54                52.0       1820.0         3.0147

[17000 rows x 4 columns]

In [ ]:
y=filtered_data.iloc[:,-1]

In [ ]:
y

0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
           ...   
16995    111400.0
16996     79000.0
16997    103600.0
16998     85800.0
16999     94600.0
Name: median_house_value, Length: 17000, dtype: float64

In [ ]:
from sklearn.linear_model import LinearRegression
algo = LinearRegression()

In [ ]:
algo.fit(x,y)

LinearRegression()

In [ ]:
machine_predictions = algo.predict(x)

In [ ]:
machine_predictions

array([ 97273.71981984, 125380.69015186,  92433.73222587, ...,
       118232.12115153,  77858.65668167, 189664.51046922])

In [ ]:
mse = np.mean((machine_predictions - y)**2)

In [ ]:
mse

6370789572.433073

In [ ]:
rmse = np.sqrt(mse)

In [ ]:
rmse

79817.22603819976

In [ ]:
#rmse is still high beacuase data is not normalize 
#now we have to normalize our data 'x' because values are varies drastically
#3 methods of normalization-
#i) min normalization
#ii) max normalization
#iii) standard normalization-converting data in z-score

In [ ]:
# if the above method still gives high rmse then 
# we have to select the input columns that are not correlated to each other which we havent done in step 1
# in step 1 we have selected those input columns which are highly correlated to output column
# if we dont select those input columns which have no correlation among themselves then we will not be able to create a good vector space(its will come in linear algebra).
# this is done by PCA- it is an unsupervised learning algo because it is used on only input feature(it is dimentionality reduction)
## interview question- difference between dimentionality reduction and feature seletion
## everything about PCA

In [ ]:
x=(x-x.mean())/x.std()
#standard normalization

In [ ]:
x


latitude  housing_median_age  total_rooms  median_income
0     -0.671500           -1.079639     1.361655      -1.252506
1     -0.573248           -0.761850     2.296540      -1.081451
2     -0.905436           -0.920744    -0.882436      -1.170071
3     -0.928830           -1.159087    -0.524171      -0.362590
4     -0.961581           -0.682402    -0.545731      -1.026424
...         ...                 ...          ...            ...
16995  2.318197            1.859916    -0.195722      -0.799975
16996  2.369663            0.588757    -0.135170      -0.715705
16997  2.907715           -0.920744     0.015292      -0.446650
16998  2.889000           -0.761850     0.012998      -0.997758
16999  2.299482            1.859916    -0.377837      -0.455349

[17000 rows x 4 columns]

In [ ]:
y=(y-y.mean())/y.std()

In [ ]:
y

0       -1.210522
1       -1.096713
2       -1.048430
3       -1.154480
4       -1.222593
           ...   
16995   -0.826848
16996   -1.106197
16997   -0.894099
16998   -1.047568
16999   -0.971696
Name: median_house_value, Length: 17000, dtype: float64

In [ ]:
#mse and rmse are misleading ways to test 

In [ ]:
from sklearn.metrics import r2_score


In [ ]:
percentage_accuracy=r2_score(y_true=y,y_pred=machine_predictions)

In [ ]:
percentage_accuracy
#A percentage accuracy is a measure of how close a measurement or test is to the true or theoretical value of that measurement or test. This is a ratio of the difference between true and measured divided by the true value.

-50057143424.0375

In [ ]:
df=(df-df.mean())/df.std()

In [ ]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       2.619288 -0.671500           -1.079639     1.361655        1.764152   
1       2.539494 -0.573248           -0.761850     2.296540        3.230346   
2       2.494610 -0.905436           -0.920744    -0.882436       -0.866931   
3       2.489623 -0.928830           -1.159087    -0.524171       -0.480216   
4       2.489623 -0.961581           -0.682402    -0.545731       -0.506313   
...          ...       ...                 ...          ...             ...   
16995  -2.342894  2.318197            1.859916    -0.195722       -0.344985   
16996  -2.347881  2.369663            0.588757    -0.135170       -0.027072   
16997  -2.362842  2.907715           -0.920744     0.015292       -0.019955   
16998  -2.362842  2.889000           -0.761850     0.012998        0.029868   
16999  -2.387778  2.299482            1.859916    -0.377837       -0.567998   

       population  households  median_income  median_house_value  
0       -0.361173   -0.075996      -1.252506           -1.210522  
1       -0.261858   -0.099401      -1.081451           -1.096713  
2       -0.955326   -0.999223      -1.170071           -1.048430  
3       -0.796769   -0.715753      -0.362590           -1.154480  
4       -0.701809   -0.622130      -1.026424           -1.222593  
...           ...         ...            ...                 ...  
16995   -0.455262   -0.343862      -0.799975           -0.826848  
16996   -0.205230   -0.094200      -0.715705           -1.106197  
16997   -0.161670   -0.117606      -0.446650           -0.894099  
16998   -0.114626   -0.060392      -0.997758           -1.047568  
16999   -0.543252   -0.601325      -0.455349           -0.971696  

[17000 rows x 9 columns]

In [ ]:
x=df.iloc[:,0:8]

In [ ]:
x

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       2.619288 -0.671500           -1.079639     1.361655        1.764152   
1       2.539494 -0.573248           -0.761850     2.296540        3.230346   
2       2.494610 -0.905436           -0.920744    -0.882436       -0.866931   
3       2.489623 -0.928830           -1.159087    -0.524171       -0.480216   
4       2.489623 -0.961581           -0.682402    -0.545731       -0.506313   
...          ...       ...                 ...          ...             ...   
16995  -2.342894  2.318197            1.859916    -0.195722       -0.344985   
16996  -2.347881  2.369663            0.588757    -0.135170       -0.027072   
16997  -2.362842  2.907715           -0.920744     0.015292       -0.019955   
16998  -2.362842  2.889000           -0.761850     0.012998        0.029868   
16999  -2.387778  2.299482            1.859916    -0.377837       -0.567998   

       population  households  median_income  
0       -0.361173   -0.075996      -1.252506  
1       -0.261858   -0.099401      -1.081451  
2       -0.955326   -0.999223      -1.170071  
3       -0.796769   -0.715753      -0.362590  
4       -0.701809   -0.622130      -1.026424  
...           ...         ...            ...  
16995   -0.455262   -0.343862      -0.799975  
16996   -0.205230   -0.094200      -0.715705  
16997   -0.161670   -0.117606      -0.446650  
16998   -0.114626   -0.060392      -0.997758  
16999   -0.543252   -0.601325      -0.455349  

[17000 rows x 8 columns]

In [ ]:
y = df.iloc[:,-1]

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components=8)
#data projection 

In [ ]:
projected_data = pca.fit_transform(X=x)

In [ ]:
projected_data

array([[ 1.75631903, -2.08148015, -0.88136972, ...,  1.24252538,
        -0.33255452,  0.88570677],
       [ 2.8861971 , -1.78938755, -0.93345502, ...,  1.46787569,
        -0.20280905,  1.81919678],
       [-1.3755142 , -2.57719452, -0.61336601, ...,  0.73807946,
        -0.52019185, -0.06916759],
       ...,
       [-0.36298644,  3.67974154,  0.17448962, ...,  0.19681216,
        -0.16561227,  0.03006297],
       [-0.34554423,  3.69818046, -0.39720841, ...,  0.20646096,
        -0.09848192,  0.01253893],
       [-1.80221181,  3.22018488, -0.8032791 , ...,  0.21446848,
         0.11127792,  0.02202286]])

In [ ]:
linear_obj = LinearRegression()
linear_obj.fit(projected_data,y)

LinearRegression()

In [ ]:
machine_predictions = linear_obj.predict(projected_data)

In [ ]:
r2_score(y_true=y,y_pred=machine_predictions)

0.6413378529502689

In [ ]:
#dimensionality reduction has to be done next to make it more accurate
#Implementation of PCA through importing libraries:

In [ ]:
from sklearn.decomposition import PCA
import pandas as pd
import numpy as np


In [ ]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       2.619288 -0.671500           -1.079639     1.361655        1.764152   
1       2.539494 -0.573248           -0.761850     2.296540        3.230346   
2       2.494610 -0.905436           -0.920744    -0.882436       -0.866931   
3       2.489623 -0.928830           -1.159087    -0.524171       -0.480216   
4       2.489623 -0.961581           -0.682402    -0.545731       -0.506313   
...          ...       ...                 ...          ...             ...   
16995  -2.342894  2.318197            1.859916    -0.195722       -0.344985   
16996  -2.347881  2.369663            0.588757    -0.135170       -0.027072   
16997  -2.362842  2.907715           -0.920744     0.015292       -0.019955   
16998  -2.362842  2.889000           -0.761850     0.012998        0.029868   
16999  -2.387778  2.299482            1.859916    -0.377837       -0.567998   

       population  households  median_income  median_house_value  
0       -0.361173   -0.075996      -1.252506           -1.210522  
1       -0.261858   -0.099401      -1.081451           -1.096713  
2       -0.955326   -0.999223      -1.170071           -1.048430  
3       -0.796769   -0.715753      -0.362590           -1.154480  
4       -0.701809   -0.622130      -1.026424           -1.222593  
...           ...         ...            ...                 ...  
16995   -0.455262   -0.343862      -0.799975           -0.826848  
16996   -0.205230   -0.094200      -0.715705           -1.106197  
16997   -0.161670   -0.117606      -0.446650           -0.894099  
16998   -0.114626   -0.060392      -0.997758           -1.047568  
16999   -0.543252   -0.601325      -0.455349           -0.971696  

[17000 rows x 9 columns]

In [ ]:
x

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       2.619288 -0.671500           -1.079639     1.361655        1.764152   
1       2.539494 -0.573248           -0.761850     2.296540        3.230346   
2       2.494610 -0.905436           -0.920744    -0.882436       -0.866931   
3       2.489623 -0.928830           -1.159087    -0.524171       -0.480216   
4       2.489623 -0.961581           -0.682402    -0.545731       -0.506313   
...          ...       ...                 ...          ...             ...   
16995  -2.342894  2.318197            1.859916    -0.195722       -0.344985   
16996  -2.347881  2.369663            0.588757    -0.135170       -0.027072   
16997  -2.362842  2.907715           -0.920744     0.015292       -0.019955   
16998  -2.362842  2.889000           -0.761850     0.012998        0.029868   
16999  -2.387778  2.299482            1.859916    -0.377837       -0.567998   

       population  households  median_income  
0       -0.361173   -0.075996      -1.252506  
1       -0.261858   -0.099401      -1.081451  
2       -0.955326   -0.999223      -1.170071  
3       -0.796769   -0.715753      -0.362590  
4       -0.701809   -0.622130      -1.026424  
...           ...         ...            ...  
16995   -0.455262   -0.343862      -0.799975  
16996   -0.205230   -0.094200      -0.715705  
16997   -0.161670   -0.117606      -0.446650  
16998   -0.114626   -0.060392      -0.997758  
16999   -0.543252   -0.601325      -0.455349  

[17000 rows x 8 columns]

In [ ]:
y

0       -1.210522
1       -1.096713
2       -1.048430
3       -1.154480
4       -1.222593
           ...   
16995   -0.826848
16996   -1.106197
16997   -0.894099
16998   -1.047568
16999   -0.971696
Name: median_house_value, Length: 17000, dtype: float64

In [ ]:
lo = df.drop(labels=df.columns[-1],axis=1)
# if we keep inplace as true it wont change anything in the copy but it will change data in the training data
#drop function: to extract one column(last one) and saving it in X

In [ ]:
lo

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       2.619288 -0.671500           -1.079639     1.361655        1.764152   
1       2.539494 -0.573248           -0.761850     2.296540        3.230346   
2       2.494610 -0.905436           -0.920744    -0.882436       -0.866931   
3       2.489623 -0.928830           -1.159087    -0.524171       -0.480216   
4       2.489623 -0.961581           -0.682402    -0.545731       -0.506313   
...          ...       ...                 ...          ...             ...   
16995  -2.342894  2.318197            1.859916    -0.195722       -0.344985   
16996  -2.347881  2.369663            0.588757    -0.135170       -0.027072   
16997  -2.362842  2.907715           -0.920744     0.015292       -0.019955   
16998  -2.362842  2.889000           -0.761850     0.012998        0.029868   
16999  -2.387778  2.299482            1.859916    -0.377837       -0.567998   

       population  households  median_income  
0       -0.361173   -0.075996      -1.252506  
1       -0.261858   -0.099401      -1.081451  
2       -0.955326   -0.999223      -1.170071  
3       -0.796769   -0.715753      -0.362590  
4       -0.701809   -0.622130      -1.026424  
...           ...         ...            ...  
16995   -0.455262   -0.343862      -0.799975  
16996   -0.205230   -0.094200      -0.715705  
16997   -0.161670   -0.117606      -0.446650  
16998   -0.114626   -0.060392      -0.997758  
16999   -0.543252   -0.601325      -0.455349  

[17000 rows x 8 columns]

In [ ]:
pca = PCA()

In [ ]:
projected_x = pca.fit_transform(X=lo)
#orthogonal projection : 

In [ ]:
projected_x

array([[ 1.75631903, -2.08148015, -0.88136972, ...,  1.24252538,
        -0.33255452,  0.88570677],
       [ 2.8861971 , -1.78938755, -0.93345502, ...,  1.46787569,
        -0.20280905,  1.81919678],
       [-1.3755142 , -2.57719452, -0.61336601, ...,  0.73807946,
        -0.52019185, -0.06916759],
       ...,
       [-0.36298644,  3.67974154,  0.17448962, ...,  0.19681216,
        -0.16561227,  0.03006297],
       [-0.34554423,  3.69818046, -0.39720841, ...,  0.20646096,
        -0.09848192,  0.01253893],
       [-1.80221181,  3.22018488, -0.8032791 , ...,  0.21446848,
         0.11127792,  0.02202286]])

In [ ]:

projected_x= pd.DataFrame(data=projected_x,columns=["feature_"+str(i) for i in range(1,9)])

In [ ]:
projected_x


feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0       1.756319  -2.081480  -0.881370  -1.337114  -1.651573   1.242525   
1       2.886197  -1.789388  -0.933455  -0.783586  -2.406787   1.467876   
2      -1.375514  -2.577195  -0.613366  -1.696162  -0.306244   0.738079   
3      -0.711519  -2.548852   0.141955  -1.472878  -0.416020   0.671019   
4      -0.773030  -2.532043  -0.656935  -1.300804  -0.384201   0.709056   
...          ...        ...        ...        ...        ...        ...   
16995  -1.449020   3.262261  -1.159048   1.130442  -0.136775   0.223682   
16996  -0.746551   3.321160  -0.673800   0.102991  -0.052157   0.013494   
16997  -0.362986   3.679742   0.174490  -1.164276  -0.019714   0.196812   
16998  -0.345544   3.698180  -0.397208  -1.230953  -0.041079   0.206461   
16999  -1.802212   3.220185  -0.803279   1.206682  -0.008361   0.214468   

       feature_7  feature_8  
0      -0.332555   0.885707  
1      -0.202809   1.819197  
2      -0.520192  -0.069168  
3      -0.610381   0.008683  
4      -0.535308  -0.080246  
...          ...        ...  
16995   0.111321  -0.028849  
16996   0.007004   0.041341  
16997  -0.165612   0.030063  
16998  -0.098482   0.012539  
16999   0.111278   0.022023  

[17000 rows x 8 columns]

In [ ]:
#diagonal coordinates of a diagonal matrix
pca.singular_values_
#it is a vector, not a matrix

array([257.86546498, 180.04103086, 135.02958221, 118.28646973,
        49.43333185,  37.14694694,  28.14717503,  15.56080843])

In [ ]:
projected_sigma=pca.get_covariance()

In [ ]:
projected_sigma

array([[ 1.00000000e+00, -9.25208279e-01, -1.14250306e-01,
         4.70104403e-02,  7.18019559e-02,  1.01674265e-01,
         5.96277042e-02, -1.54849614e-02],
       [-9.25208279e-01,  1.00000000e+00,  1.64539031e-02,
        -3.87725742e-02, -6.93729152e-02, -1.11261361e-01,
        -7.49022967e-02, -8.03030138e-02],
       [-1.14250306e-01,  1.64539031e-02,  1.00000000e+00,
        -3.60984166e-01, -3.20434083e-01, -2.95889805e-01,
        -3.02754191e-01, -1.15931625e-01],
       [ 4.70104403e-02, -3.87725742e-02, -3.60984166e-01,
         1.00000000e+00,  9.28402988e-01,  8.60170341e-01,
         9.19018298e-01,  1.95382807e-01],
       [ 7.18019559e-02, -6.93729152e-02, -3.20434083e-01,
         9.28402988e-01,  1.00000000e+00,  8.81168574e-01,
         9.80920092e-01, -1.34946823e-02],
       [ 1.01674265e-01, -1.11261361e-01, -2.95889805e-01,
         8.60170341e-01,  8.81168574e-01,  1.00000000e+00,
         9.09246530e-01, -6.37629138e-04],
       [ 5.96277042e-02, -7.490229

In [ ]:
  #PCA from Scratch :

In [ ]:
X_original_zeromean=lo-lo.mean()

In [ ]:
X_original_zeromean = np.array(lo)

In [ ]:
X_original_zeromean

array([[ 2.61928796, -0.67150048, -1.07963939, ..., -0.36117339,
        -0.07599573, -1.25250632],
       [ 2.53949409, -0.57324751, -0.7618496 , ..., -0.26185753,
        -0.09940148, -1.08145117],
       [ 2.49461003, -0.90543615, -0.9207445 , ..., -0.95532614,
        -0.99922267, -1.17007074],
       ...,
       [-2.36284218,  2.90771515, -0.9207445 , ..., -0.16167048,
        -0.11760596, -0.44665   ],
       [-2.36284218,  2.88900029, -0.7618496 , ..., -0.11462613,
        -0.06039189, -0.99775783],
       [-2.38777776,  2.29948243,  1.85991613, ..., -0.54325246,
        -0.60132486, -0.45534949]])

In [ ]:
sigma_original= (1/lo.shape[0])*np.matmul(X_original_zeromean.T,X_original_zeromean)

In [ ]:
sigma_original

array([[ 9.99941176e-01, -9.25153855e-01, -1.14243586e-01,
         4.70076750e-02,  7.17977323e-02,  1.01668284e-01,
         5.96241967e-02, -1.54840505e-02],
       [-9.25153855e-01,  9.99941176e-01,  1.64529352e-02,
        -3.87702934e-02, -6.93688344e-02, -1.11254817e-01,
        -7.48978907e-02, -8.02982901e-02],
       [-1.14243586e-01,  1.64529352e-02,  9.99941176e-01,
        -3.60962931e-01, -3.20415234e-01, -2.95872400e-01,
        -3.02736382e-01, -1.15924805e-01],
       [ 4.70076750e-02, -3.87702934e-02, -3.60962931e-01,
         9.99941176e-01,  9.28348376e-01,  8.60119743e-01,
         9.18964238e-01,  1.95371314e-01],
       [ 7.17977323e-02, -6.93688344e-02, -3.20415234e-01,
         9.28348376e-01,  9.99941176e-01,  8.81116741e-01,
         9.80862391e-01, -1.34938885e-02],
       [ 1.01668284e-01, -1.11254817e-01, -2.95872400e-01,
         8.60119743e-01,  8.81116741e-01,  9.99941176e-01,
         9.09193045e-01, -6.37591631e-04],
       [ 5.96241967e-02, -7.489789